#import "fonts.typ": *
#import "inline.typ": *
#import "options.typ": *
#let jsarticle-default-options = (
  document: (
    title: [],
    subtitle: [],
    author: [],
    other: [],
    date: "",
    logo: [],
    authors: none,
    abstract: [],
    keywords: (),
    title-page: "cover",
    author-layout: "inline",
  ),
  page: (
    bind: "none",
    margin-ratio: "optical",
    paper-size: "a4",
    doc-type: "article",
    cols: 1,
    h1-break: "adaptive",
    column-gutter: 2em,
    chapter-format: ("第", "章"),
    margin: auto,
    header: auto,
    footer: auto,
  ),
  typography: (
    font-size: auto,
    text-width: auto,
    marginal-outset: auto,
    lines-per-page: auto,
    baseline-ratio: auto,
    cjk-height: 0.88,
    cjk-scale: 0.925em,
    latin-scale: 1em,
    latin-baseline: 0em,
    latin-tracking: 0em,
    latin-light-weight: false,
    language-aware: true,
    ambient-language: "ko",
    japanese-scale: auto,
    chinese-scale: auto,
    korean-leading-ratio: auto,
    western-leading-ratio: auto,
    japanese-leading-ratio: auto,
    chinese-leading-ratio: auto,
    strong-latin-scale: auto,
    strong-latin-baseline: 0em,
    optical-adjustments: true,
    optical-profiles: default-optical-profiles,
    inline-math-display-style: false,
    inline-math-bounds: false,
    math-font: font-math,
    cjk-spacing: none,
    inline-atom-particles: auto,
  ),
  fonts: (
    // One direct composite per canonical role. This is intentionally one map:
    // language remains a rule condition inside each composite, never another
    // font configuration hierarchy.
    composites: js-default-fontsets,
    body-family: "serif",
    strong-family: "gothic",
    heading-family: "gothic",
    footnote-family: "footnote",
    ruby-family: auto,
    strong-weight: "medium",
  ),
  horizontal: (
    normalization: (
      enabled: false,
      punctuation: true,
      spaces: true,
      collapse-punctuation-space: true,
    ),
  ),
  vertical: (
    page-start: false,
    heading-mode: "semantic",
    unicode-fallbacks: false,
    collapse-punctuation-space: true,
    korean-fullwidth-spaces: false,
    boundary-spacing: auto,
    latin-orientation: "rotate",
    tcy-max-digits: 2,
    tracking: 0pt,
    ruby-size: 0.5em,
    ruby-gap: 0em,
    ruby-overflow: "reserve",
    ruby-overhang: 0.5em,
    width: auto,
    height: auto,
    columns: 1,
    rows: 1,
    line-gap: 0.6em,
    column-gap: 2em,
    row-gap: 2em,
    row-fit-threshold: 1.5,
    line-overhang-threshold: 0.5em,
    min-final-line-chars: 2,
    min-fragment-chars: 2,
    min-fragment-languages: ("ko",),
    justify-languages: ("ko",),
    justify: true,
    orphan-lines: 2,
    widow-lines: 2,
    stream-gap: 0.6em,
    font-family: auto,
    strong-family: auto,
    heading-family: auto,
    ruby-family: auto,
  ),
)

// V2 public constructor. Defaults and validation live in exactly one record;
// callers can supply only the groups they intend to change.
#let jsarticle-options(..groups) = resolve-options(
  jsarticle-default-options,
  groups.named(),
  opaque: (
    "options.typography.optical-profiles",
    // A document supplies a partial role map. Role composites themselves are
    // opaque values and are merged once below, after role aliases are known.
    "options.fonts.composites",
  ),
)
