#import "../template.typ": *

= 

== Introduction 

After achieving a high score on the March CSAT mock exam, my teacher asked the top scorers in each subject to come to the front of the class and share their study methods. That was the moment I realized I had absolutely nothing to say for my classmates. I didn't have some kind of a specific "study method" for English at all. Standing there in front of everybody, I could only repeat the same old advice: "Don't chop the sentences and flip'em around up to fit Korean word order -- just read them from left to right and then let the information stack up naturally," or "Vocab is everything, you cannot understanding anything if you don't know the words."

My actual strategy for reading comprehension tests was just read the text and pick the #strike[freaking] answer. Even though recent CSAT questions feature ambiguous and deceptive choices designed to confuse us, this strat had consistently kept my position in the "fixed 90%+ zone"#footnote[고정 1등급...] since when I was a first grader.

However, this made me curious: If this is not _the_ way to study English, and I am not studying English like everyone else, how did I get good at it? What exactly was the underlying mechanism of my "proficiency" that gave me good grades? After some research and also looking back at my past linguistic journey, I was led to a somewhat fundamental conclusion: fluency doesn't come from breaking down grammar rules like a math formula. Instead, it comes from soaking in a massive amount of input data, finding real-world reasons to use it, and making your brain realise that this language actually _matters_ to your daily life. 

== The Scaling Law

Since I was a child, I was naturally exposed to English. Back then, I read a lot of silly English novels that my parents sneaked into my room such as the _Franny K. Stein_ series, _My Weird School_ series, Roald Dahl's#footnote[로알드 달. A famous children book writer. He has written "Matilda", "Charile and the Chocolate Factory", and many more.] books, etc. I also remember watching many crappy Minecraft house building   videos that I had somehow found entertaining as a toddler. I never tried to actually _study_ English as a language or a subject. In fact my father wanted me to study it so badly, I resisted it at first because it wasn't fun at all. Even so, he would always quiz me on vocabulary, expressions, and idioms, which actually turned out to be incredibly helpful later on.

Today, I spend time in English environments almost every day exploring various media and online communities related to my interests in math, physics, computer science, typesetting etc. Consistently consuming this authentic content made my brain completely familiar with the structures and phrasing of the language. Simply put, my approach to learning English was based on massive exposure to authentic, understandable input data. Interestingly, this is very similar to how modern Large Language Models (LLMs) learn. Tech companies like OpenAI found out that the most effective way to increase the accuracy and quality of their models was to feed them a tremendous amount of data during the training phase. This principle, known as "the scaling law," is why everyone today is crazy about data centers and semiconductors that is capable of processing massive data in (linear algebraic) matrix formats. Therefore, "learning like a language model" seems to be a good analogy for my learning experience.

== Immersive Learning

The human brain is turns out to be an incredibly efficient machine designed for survival, which means it is constantly filtering out information it deems unnecessary. When a language is treated purely as an academic subject, or a "language", the brain may categorise it as a temporary chore. Because there is no immediate, real-world consequence to forgetting a grammar rule, the data is easily purged from short-term memory. This is why immersive learning turns out to be effective: it bypasses this cognitive "filter" by shifting the language from an object of study into a necessary tool for daily life and personal desires.

In a traditional(the "i gotta study" situation) setting, words and phrases are learned through sterile, isolated translation lists, often in a 1 to 1 correspondence to our native language. In contrast, an immersive environment, such as reading books or participating in an online community, ties language directly to realistic actions, logical problems and deep personal interests. When a new word is encountered while trying to do someting else rather than studying the language itself, that word is no longer just an abstract vocab item to be tested on. It becomes an essential material to solving a problem. This practical utility signals to the brain that the information is critical, prompting it to secure it into long-term memory.

When we consciously try to "study" a language, we often experience anxiety about making mistakes or failing to memorize rules perfectly. This anxiety creates a mental block that slows down natural language acquisition. Immersive learning reduces this barrier, and allows us to be deeply invested only in the _content_ itself -- whether it is an entertaining video or a complex mathematical theory -- our conscious mind is entirely focused on comprehending the meaning, not analyzing the grammar and the lignuistic factors. By prioritizing the message over the structure, the brain naturally and effortlessly absorbs syntax and vocabulary through implicit learning, kind of mimicking how we acquired our native language as children.

Furthermore, this immersion factor becomes even more important as we grow older. While children can absorb languages almost effortlessly due to high brain plasticity, adolescent and adult brains require a much stronger stimulus to reshape their neural networks. There is a well-known theory that as the brain matures, its natural capacity for effortless language acquisition decreases. Therefore, passive exposure is not enough. Deliberate, high-relevance immersion acts may be the key. I had discovered that the method of exploiting these kind of mechanisms of the brain is so called the "Immersive Learning" method especially in language learning Reddits, and its effectiveness has been proved by countelss language learners, now including me.

== Application in learning Japanese

To see if this theory actually works outside of my childhood English experience, I accidentally started a living experiment. Last December, driven by a consistent need to read academic texts for my science studies and also some of the more minor reasons#footnote[ Something like: - Japan is our neighboring country - I want a better understanding in the overall CJK languages - Not one but two Japanese scientists were awarded the Nobel prize(biology, chemistry) in 2025 - I want to take a look at what the Japanese government is insisting in sensitive political issues related to Korea, and what the Japanese people are thinking about them
], I began learning Japanese.

I had to balance this with my school workload, so I never had time to actually sit down and invest some time in learning Japanese intensely. I didn't even have a textbook to work on. Instead, I just learned the writing system, and after that, dove straight into what I cared about. I read math textbooks in Japanese, the one I like the most is the one by Hal Tasaki#footnote[田崎晴明, 타사키 하루아키. Google scholar page: https://scholar.google.com/citations?user=0Q0esHoAAAAJ&hl=en], a famous physicist and a professor of Gakushuin University#footnote[学習院大学, 가쿠슈인대학]. I was introduced to a typesetting community by a Russian friend(who is also interested in learning Japanese), called "くみはんクラブ"#footnote[組版クラブ. 한국어로 하면 조판 클럽] and learned a lot about CJK typesetting and Chinese characters(漢字) too.

The results over just five to six months have been shocking. First, I felt like I would never be able to be fluent in this language, but after all, just using the language and being exposed made me quite fluent, so to say. I can now read books and watch videos in Japanese without major issues. I can also write and speak what I want to say. The only times I struggle is when I run into vocabulary issues, as I hadn't have enough time to properly study the vocabulary.